--后台管理员表
CREATE TABLE T_Admin(
	ID int PRIMARY KEY IDENTITY(1,1),
	UserName VARCHAR(32) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Mobile VARCHAR(11),
	Email VARCHAR(200),
	Realname NVARCHAR(50),
	IsDisable INT DEFAULT(0),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)


--后台管理操作日志表
CREATE TABLE T_AdminLog(
	ID int PRIMARY KEY IDENTITY(1,1),
	AdminID INT NOT NULL,
	Title NVARCHAR(255),
	Content NVARCHAR(max),
	IP VARCHAR(50),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)

--系统配置表
CREATE TABLE T_SystemConfig(
	ID int PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(50),
	Code VARCHAR(50) NOT NULL,
	Value NVARCHAR(MAX),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)

--轮播图片表
CREATE TABLE T_ImgPlay(
	ID int PRIMARY KEY IDENTITY(1,1),
	NavigationID INT NOT NULL,
	Type INT NOT NULL DEFAULT(0),
	Name NVARCHAR(500),
	Title NVARCHAR(500),
	Subhead nVARCHAR(20),
	ImgUrl NVARCHAR(500),
	LinkUrl NVARCHAR(500),
	Target INT NOT NULL DEFAULT(0),
	IsDisable INT DEFAULT(0),
	Sort INT NOT NULL DEFAULT(0),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)

--友情链接表
CREATE TABLE T_FriendlyLink(
	ID int PRIMARY KEY IDENTITY(1,1),
	Type INT NOT NULL DEFAULT(0),
	Name NVARCHAR(500),
	Title NVARCHAR(500),
	ImgUrl NVARCHAR(500),
	LinkUrl NVARCHAR(500),
	Target INT NOT NULL DEFAULT(0),
	IsDisable INT DEFAULT(0),
	Sort INT NOT NULL DEFAULT(0),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)


--导航表
CREATE TABLE T_Navigation(
	ID int PRIMARY KEY IDENTITY(1,1),
	Type INT NOT NULL DEFAULT(0),
	ParentId INT NOT NULL,
	Name NVARCHAR(500),
	Url NVARCHAR(500),
	Target INT NOT NULL DEFAULT(0),
	IsDisable INT DEFAULT(0),
	CanDisable INT DEFAULT(0),
	Sort INT NOT NULL DEFAULT(0),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)

--文章分类表
CREATE TABLE T_Category(
	ID int PRIMARY KEY IDENTITY(1,1),
	ParentId INT NOT NULL,
	ParentIdPath  NVARCHAR(255) NOT NULL,
	Name NVARCHAR(500),
	ImgUrl NVARCHAR(500),
	IsDisable INT DEFAULT(0),
	Sort INT NOT NULL DEFAULT(0),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)

--文章表
CREATE TABLE T_News(
	ID int PRIMARY KEY IDENTITY(1,1),
	CategoryId INT NOT NULL,

	Title NVARCHAR(500),
	ImgUrl NVARCHAR(500),
	Author NVARCHAR(50),
	Summary NVARCHAR(500),
	Source NVARCHAR(500),
	Content NVARCHAR(max),
	ReleaseTime DATETIME,
	ViewCount BIGINT NOT NULL DEFAULT(0),
	MetaKeywords NVARCHAR(500),
	MetaDescription  NVARCHAR(500),
	 
	IsDisable INT DEFAULT(0),
	Sort INT NOT NULL DEFAULT(0),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE()),
	CreateAdminId INT NOT NULL DEFAULT(0),
	UpdateTime DATETIME NOT NULL,
	UpdateAdminId  INT NOT NULL DEFAULT(0)
)

--单页面内容表
CREATE TABLE T_PageContent(
	ID int PRIMARY KEY IDENTITY(1,1),
	ContentType INT NOT NULL DEFAULT(0),
	NavigationID INT NOT NULL,
	Title nVARCHAR(500),
	Content nVARCHAR(max),
	ImgUrl NVARCHAR(500),
	IconCode VARCHAR(100),
	IsHomePageShows INT DEFAULT(0),
	SectionName nVARCHAR(20),
	Subhead nVARCHAR(20),
	IsDisable INT DEFAULT(0),
	Sort INT NOT NULL DEFAULT(0),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdateTime DATETIME NOT NULL
)


--招聘信息
CREATE TABLE T_Recruitment(
	ID int PRIMARY KEY IDENTITY(1,1),
	JobTitle nVARCHAR(100),
	Location nVARCHAR(20),
	Salary VARCHAR(20),
	RecruitingNum INT,
	JobDescription nVARCHAR(max),

	Sort INT NOT NULL DEFAULT(0),

	CreateTime DATETIME NOT NULL DEFAULT(GETDATE()),
	CreateAdminId INT NOT NULL DEFAULT(0),
	UpdateTime DATETIME NOT NULL,
	UpdateAdminId  INT NOT NULL DEFAULT(0)
)

--网站主体者信息
CREATE TABLE T_OwnerInfo(
	ID int PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(500),
	LinkMan VARCHAR(200),
	Email VARCHAR(200),
	Mobile NVARCHAR(500),
	Address  NVARCHAR(500),
	MapIFrameUrl NVARCHAR(max),
	CreateTime DATETIME NOT NULL DEFAULT(GETDATE())
)